name: 'Node.js CI'
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build and Test PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_REGISTRY_USER}} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD}}
      - run: docker build -t sample-project/test-image -f Dockerfile.dev .

    # Build and Deploy with node in CI environment
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: 18
    #   - run: npm install
    #   - run: npm run build --if-present
    #   - run: npm test
