name: Release
on:
  push:
    branches: [main]
jobs:
  stage_build:
    name: Tag and Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @codedependant/semantic-release-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD}}
  deploy_prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment:
      name: production
      url: its a secret
    steps:
      - run: Deploying to prod!
