name: Release
on:
  push:
    branches: [release]
jobs:
  stage_build:
    name: Tag and Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @codedependant/semantic-release-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD}}
      - name: Deploy Stage
        env:
          name: stage
          url: its a secret
        run: echo Deploying to Stage
      - name: Verify Stage
        env:
          name: stage
          url: its a secret
        run: echo Running Automation in Stage

  # deploy_stage:
  #   name: Deploy Stage
  #   needs: stage_build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: stage
  #     url: its a secret
  #   steps:
  #     - run: echo Deployed to Stage!
  # verify_stage:
  #   name: Verify Stage
  #   needs: deploy_stage
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: stage
  #   steps:
  #     - run: echo The Automation Tests Pass!
