name: 'Semantic Release'
on:
  pull_request:
    branches:
      - develop
jobs:
  release:
    name: Print Release Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # you'll need to add an `id` in order to access output variables
      - uses: codfish/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: echo ${{ steps.semantic.outputs.release-version }}

      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

      - uses: codfish/some-other-action@v1
        with:
          release-version: ${{ steps.semantic.outputs.release-version }}
