name: Release Actions
on:
  push:
    branches: [main, alpha]
jobs:
  release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
